<?php
// AUTOGENERATED
// PHP 5.2 Support (recommended php version)
//error_reporting(E_ALL);ini_set('display_errors',1);

$prname = "smcontents";

$config = array();
$config['dbhost'] = 'localhost';

$config['dbname'] = 'polovodie_db';
$config['dbuser'] = 'polovodie_user';
$config['dbpass'] = 'sdhQddA78ds2ejq';
//настройка типа кодировки соединения с MYSQL
$config['mysql_set_names'] = 'utf8';


$config['site_name'] = 'Половодье';
$config['site_dir'] = 'polovodie';

