<?php
//date_default_timezone_set('Asia/Yekaterinburg');
error_reporting(E_ERROR);
//error_reporting(E_ALL & ~E_NOTICE); // todo: вернуть
ini_set('display_errors', true);



define("SITE_ID", "");

$admin_ar_m = array(
    '1' => 'январь', '2' => 'февраль', '3' => 'март', '4' => 'апрель', '5' => 'май', '6' => 'июнь', '7' => 'июль', '8' => 'август', '9' => 'сентябрь', '10' => 'октябрь', '11' => 'ноябрь', '12' => 'декабрь'
);

$ar_mon = array('1' => 'Января', '2' => 'Февраля', '3' => 'Марта', '4' => 'Апреля', '5' => 'Мая', '6' => 'Июня', '7' => 'Июля', '8' => 'Августа', '9' => 'Сентября', '10' => 'Октября', '11' => 'Ноября', '12' => 'Декабря');


$ar_mon_count = array('1' => 31, '2' => 28, '3' => 31, '4' => 30, '5' => 31, '6' => 30, '7' => 31, '8' => 31, '9' => 30, '10' => 31, '11' => 30, '12' => 31);

$substep = 5;

try {
    $dir = dirname(__FILE__) . '/';
    if (file_exists($dir . 'config.php'))
        require $dir . 'config.php';
    else throw new Exception('config.php not found');
} catch (Exception $e) {
    file_put_contents($dir . 'config.php', <<<PHP
<?php
// AUTOGENERATED
// PHP 5.2 Support (recommended php version)
\$prname = "smcontents";

\$config = array();
\$config['dbhost'] = 'localhost';

\$config['dbname'] = 'devel_cms_development';
\$config['dbuser'] = 'smdevel';
\$config['dbpass'] = 'smdevel';
//настройка типа кодировки соединения с MYSQL
\$config['mysql_set_names'] = 'utf8';


\$config['site_name'] = 'SM::CMS Project';
PHP
    );
    require 'config.php';
}

$array_admin_add = array
(
    '0' => '4',
);

//устарело: сейчас врапперы определяются в самих модулях
//оставим для совместимости
$wrappers = array
(
    'index' => array(module => 'text', html => 'index.html')
);

// сопоставление шаблонов папки и html-шаблона


$config['user_file_moduls'] = '../inc/modules/';
$config['user_file_templetes'] = '../templates/';
$config['smimw'] = '400';
$config['smimh'] = '400';
$config['md5'] = '';
$config['upload_dir'] = '../images/';

$config["DOCUMENT_ROOT"] = rtrim($_SERVER['DOCUMENT_ROOT'], '/') . '/' . $config['site_dir'] . '/';
//$config["DOCUMENT_ROOT"] = $_SERVER['DOCUMENT_ROOT'].'addsite/cms.smhost.ru/';
$config['server_url'] = 'http://' . $_SERVER['SERVER_NAME'] . '/' . $config['site_dir'] . '/';
$config['admin_IP'] = array('213.242.253.169', '46.163.171.58', '89.113.194.77'); //IP адреса админов-разработчиков

$config['upload_url'] = $config['server_url'] . 'img/';
$config['upload_file'] = $config['server_url'] . 'files/';
$config['upload_doc'] = $config['server_url'] . 'documents/';

$config['admin_login_page'] = 'admin_login.php';
$config['truncate_length'] = '20';

$config['url_fonts'] = "libs/fonts/"; // адрес до шрифтов
$config['form_img'] = "libs/imgcode/"; // адрес до каталога с картинками
$config['form_imgurl'] = "http://" . $_SERVER['SERVER_NAME'] . '/' . $config['site_dir'] . "/libs/imgcode/"; // адрес до каталога с картинками

$texts['sql_connection_error'] = 'Невозможно подключиться к серверу баз данных.';
$texts['sql_db_selection_error'] = 'Невозможно выбрать базу данных.';

$texts['back'] = 'назад';
$texts['up'] = 'назад';
$texts['mainpage'] = 'Главная страница';
$texts['search_page_number'] = ', страница ';
$texts['close'] = 'закрыть';
$config['path_separator'] = ' / ';


//настройки для интерфейса системы администрирования с v 2.0.0.

$config['admin_menu_width'] = '300'; // px - начальная ширина дерева разделов px
$config['admin_preload_tree'] = true; // подгружать дерево разделов в iframe, либо загружать при вызове дерева разделов
$config['admin_is_moder'] = true; // - включить модераторов
$config['admin_version'] = 'SM:Contents  v 2.3.0'; // версия

if (!function_exists('parse_version')) {
    function parse_version($string)
    {
        /**
         * функция парсит название версию админки из переменной $config['admin_version'], либо из той, что ему подсунуть.
         * @var $productname string код (чпу) названия продукта sm-contents в данном случае
         * @var $major int мажорная версия
         * @var $minor int минорная версия
         * @var $subversion int|string субверсия проекта (возможно, символьная)
         */
        list($productname, $version) = explode('v', strtolower($string), 2);
        list($major, $minor, $other) = explode('.', preg_replace('/\s/m', '', $version), 3);
        $productname = preg_replace(array('/[^a-z0-9]/m', '/-{2,}/m'), '-', trim($productname));
        $other = preg_replace(array('/[^a-z0-9]/m', '/-{2,}/m'), '-', trim($other));
        return array($productname, $major . '.' . $minor, $other);
    }
}

date_default_timezone_set('Asia/Yekaterinburg');

//экспорт из csv блоков
/*
	$config['admin_csv_import'] = array	(
			array (	'template'=>'tovar',
					'merge_compare_field'=>'art,title',
					'default_regime'=>'merge'
			),
			array (	'template'=>'news',
					'merge_compare_field'=>'art,title',
					'default_regime'=>'merge'
			),
				//		'template'=>'шаблон блока',
				//		'merge_compare_field'=>'по какому полю сравнивать. если указано сравнение, то будет обновляться
				//			информация 	во всех полях, кроме этого, по нему будет поиск',
				//		'default_regime'=>'режим по умолчанию, merge или delete'
	);

	$config['admin_all_blocks'] = array	(
			array (
				'template'=>'news',
				'parent'=>'1',
				'select_size'=>'20',
				'font_size'=>'10px',
			),
	);

*/
/*
кеширование
    0 - отключено
    1 - локальное
    2 - глобальное (страница целиком)
*/
$config['cache'] = 0;

//включение режима "автодополнения" для модулей
//при включении будут самостоятельно создаваться необходимые методы у модулей
$config['metamodule_autocreate'] = 1;

// редактор
# $wisi_wisi = 2;
$wisi_wisi = 3;


$code_imgclass['left'] = 'img-lft';
$code_imgclass['right'] = 'img-rgh';
$code_imgclass[''] = '';
$code_imgclass['baseline'] = 'baseline';
$code_imgclasses = array(left, right, baseline, '');

//  $code_plus = '<div class="plus"><a href="{href}" target="{target}" {onclick}></a></span> ';
/*$code_open['left'] = '<div class="img-lft">';
$code_open['right'] = '<div class="img-rgh">';//<div class="rltv-img">
$code_open['baseline'] = $code_open[''] = '<div>';
$code_close[ 'left'] = '</div>';
$code_close['right'] = '</div>';
$code_close['baseline'] = $code_close[''] = '</div>';*/

?>